name: Update airtable from mysql
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
jobs:
  update-airtable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
        cache: 'pip'
    - name: Install
      run: |
        pip3 install -r requirements.txt
        pip3 install playwright
        playwright install firefox
        python3 main.py
      env:
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        AIRTABLE_APIKEY: ${{ secrets.AIRTABLE_APIKEY }}
